---
title: "Skill acquisition as a function of age, hand and task difficulty: Interactions between cognition and action"
type: "article"
author: 
  - name: Rachael K. Raw
    orcid: 0000-0001-7593-3436
  - name: Richard M. Wilkie
    orcid: 0000-0003-4299-7171 
  - name: Richard J. Allen
    orcid: 0000-0002-1887-3016
  - name: Matthew Warburton
    orcid: 0000-0001-5309-4424
  - name: Matteo Leonetti
    orcid: 0000-0002-3831-2400
  - name: Justin H. G. Williams
  - name: Mark Mon-Williams
    orcid: 0000-0001-7595-8545
date: "2019-02-07"
year: 2019
publication: "PLoS ONE"
doi: "https://doi.org/10.1371/journal.pone.0211706 "
toc: false
pub-info:
  reference: >-
   Raw, R. K., Wilkie, R. M., Allen, R. J., <strong>Warburton, M.</strong>, Leonetti, M., Williams, J. H. G. & Mon-Williams, M. (2019). Skill acquisition as a function of age, hand and task difficulty: Interactions between cognition and action. <em>PLoS ONE, 14</em>(2), e0211706 doi: <a href="https://doi.org/10.1371/journal.pone.0211706">10.1371/journal.pone.0211706</a>
   
categories:
  - skill acquisition
---

## Abstract

Some activities can be meaningfully dichotomised as ‘cognitive’ or ‘sensorimotor’ in nature—but many cannot. This has radical implications for understanding activity limitation in disability. For example, older adults take longer to learn the serial order of a complex sequence but also exhibit slower, more variable and inaccurate motor performance. So is their impaired skill acquisition a cognitive or motor deficit? We modelled sequence learning as a process involving a limited capacity buffer (working memory), where reduced performance restricts the number of elements that can be stored. To test this model, we examined the relationship between motor performance and sequence learning. Experiment 1 established that older adults were worse at learning the serial order of a complex sequence. Experiment 2 found that participants showed impaired sequence learning when the non-preferred hand was used. Experiment 3 confirmed that serial order learning is impaired when motor demands increase (as the model predicted). These results can be captured by reinforcement learning frameworks which suggest sequence learning will be constrained both by an individual’s sensorimotor ability and cognitive capacity.