project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Matthew Warburton"
  search: true
  navbar:
    background: dark
    type: light
    # left:
    right:
      - text: About
        href: index.qmd
      - text: Publications
        href: publications/index.qmd
  google-analytics:
    tracking-id: "G-B3R4LM1ZGR"
    storage: none
    anonymize-ip: true
      

  # page-footer:
  #   border: true
  #   left: "Matthew Warburton"

format:
  html:
    theme: [cosmo]
    css: css/style.css
    toc: false

editor: source